version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    image: ${USERNAME}/ui:1.0
    volumes:
      - ui_vol:/app
    command: [ "puma", "--debug", "-w", "2" ]
    ports:
      - "9292:9292/tcp"
    networks:
      - reddit
  post:
    image: ${USERNAME}/post:1.0
    volumes:
      - post_vol:/app
    networks:
      - reddit
  comment:
    image: ${USERNAME}/comment:1.0
    volumes:
      - comment_vol:/app
    command: [ "puma", "--debug", "-w", "2" ]
    networks:
      - reddit

volumes:
  post_db:
  ui_vol:
  post_vol:
  comment_vol:

networks:
  reddit:
