version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${SERVICE_VER}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${SERVICE_VER}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${SERVICE_VER}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
